Hackathon_2024/Chat_Fora_S2/urls.py
from django.contrib import admin
from django.urls import path
from .views import conversation_list,conversation_detail,messagerie,create_conversation,start_conversation,add_participant

app_name = 'Chat_Fora_S2'
urlpatterns = [
    path('', conversation_list, name = 'Acceuil'),
    path('Acceuil', conversation_list, name = 'Acceuil'),
    path('messagerie/<int:conversation_id>/', messagerie, name = 'messagerie'),
    path('conversations/<int:conversation_id>/', conversation_detail, name='conversation_detail'),
    path('create', create_conversation, name = 'create'),
    path('start/<str:titre>/<str:other_user_name>',start_conversation ,name = 'start_conversation'),
    path('add/<int:conversation_id>/<str:other_user_name>',add_participant)
]

Hackathon_2024/HackVerse_2024/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index,register,ogin,register_user
from Get_A_Job_S1.views import handler


urlpatterns = [
    path('admin/',  admin.site.urls),
    path('job/',include('Get_A_Job_S1.urls')),
    path('Chat/',include('Chat_Fora_S2.urls')),
    path('',register_user),
    path('login',ogin),
    path('index',index,name='index'),
    path('accounts/login/',handler),
]

Hackathon_2024/Chat_Fora_S2/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Conversation(models.Model):
    participants = models.ManyToManyField(User)
    titre = models.CharField(max_length=200)

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # sender
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

class ConversationOO(models.Model):
    Username = models.CharField(max_length=200)
    titre = models.CharField(max_length=200)

Hackathon_2024/Chat_Fora_S2/forms.py
from django import forms
from .models import Conversation,Message,ConversationOO

class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = ['titre','participants']
        
class ConversationFormOO(forms.ModelForm):
    class Meta:
        model = ConversationOO
        fields = ['titre','Username']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['titre'].widget.attrs['placeholder'] = "Titre de la conversation"
        self.fields['Username'].widget.attrs['placeholder'] = "Nom d'un participant"
        
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']
        
    
        

Hackathon_2024/Chat_Fora_S2/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Conversation, Message,ConversationOO
from .forms import ConversationForm,MessageForm,ConversationFormOO
from django.urls import reverse

# Create your views here.
@login_required
def conversation_list(request):
    conversations = Conversation.objects.filter(participants = request.user)
    # conversations.delete()
    return render(request, 'Chat_Fora_S2/Acceuil.html', {'conversations': conversations,'user':request.user})


@login_required
def conversation_detail(request, conversation_id):
    conversation = Conversation.objects.get(id=conversation_id)
    messages = Message.objects.filter(conversation=conversation)
    return render(request, 'Chat_Fora_S2/conversation_detail.html', {'conversation': conversation, 'messages': messages})

def messagerie(request,conversation_id):
    conversation = Conversation.objects.get(id=conversation_id)
    messages = Message.objects.filter(conversation=conversation)
    # messages.delete()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
           
            message = Message.objects.create(conversation = conversation,user = request.user,content = content)
            
    else :
        form = MessageForm()
    
    return render(request, 'Chat_Fora_S2/messagerie.html', {'form': form ,'conversation':conversation ,'messages': messages ,'user':request.user})

def create_conversation(request):
    conversations = Conversation.objects.filter(participants = request.user)
    users = User.objects.all()
    if request.method == 'POST':
        form = ConversationFormOO(request.POST)
        if form.is_valid():
            titre = form.cleaned_data['titre']
            current_user = request.user
            if User.objects.filter(username=form.cleaned_data['Username']).exists() == True:
                other_user = User.objects.get(username=form.cleaned_data['Username'])
                
                return redirect('start_conversation',titre,other_user)
            else:
                return render(request, 'Chat_Fora_S2/erreur_user.html')
        
    else :
        form = ConversationFormOO()
        return render(request, 'Chat_Fora_S2/create_conversation.html' ,{'form':form ,'users':users})
     
    return render(request, 'Chat_Fora_S2/Acceuil.html', {'conversations': conversations})

def start_conversation(request,titre,other_user_name):
    #Verification si l'utilisateur est authentifié
    if request.user.is_authenticated:
        #Obtenir l'utilisateur actuel et l'utilisateur cible
        current_user = request.user
        
        other_user = User.objects.get(username=other_user_name)
            
            #Creation d'une nouvelle instance de modele Conversation
        if Conversation.objects.filter(titre=titre).exists() == False:
            conversation = Conversation.objects.create(titre=titre)
                
                #Ajout des participants a la conversation 
            conversation.participants.add(current_user,other_user)
                
            #Redirection de l'utilisateur vers la page de messagerie
        else :
            conversation = Conversation.objects.get(titre=titre)
        return redirect(reverse('Chat_Fora_S2:messagerie',args=[conversation.id]))
        
    
    else:
        return redirect('login')
    
    return redirect('Acceuil')

def add_participant(request,id,other_user_name):
    #Obtenir l'utilisateur actuel et l'utilisateur cible
    current_user = request.user
    conversation = Conversation.objects.get(id=id)
    print(conversation)
    # if User.objects.filter(username=other_user_name).exists() == True:
    #     other_user = User.objects.get(username=other_user_name)
    #     old_participants = conversation.participants
    #     # conversation.participants.add(other_user)
    # else:
    #     return render(request, 'Chat_Fora_S2/erreur_user.html')
    
    
    return render(request,'Chat_Fora_S2/add_part.html')

Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/Acceuil.html
{% load static%}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat interactif</title>
    <style>
		/* Styles pour l'entête */
.header {
	position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: #00a86b;
  color: white;
  padding: 10px;
  z-index: 999; /* Assurez-vous que l'entête est au-dessus du contenu */
}
button.btn-postuler {
  color: blue;
  width: 30%;
  padding: 1%;
  font-size: larger;
}
/* Styles pour les boutons de l'entête */

.options-button {
  background-color: transparent;
  border: none;
  color: white;
  cursor: pointer;
  font-size: 16px;
}

		
        /* Styles pour la liste des conversations */
        .conversation-list {
            list-style: none;
            padding: 0;
        }
		.listOfconversations::before{
			content: "";
			display: block;
			margin-top: 100px;
		  }

        .conversation-item {
			display: flex;
			align-items:center;
            border: none;
            padding: 10px;
            margin-bottom: 10px;
            background-color: #f9f9f9;
        }

		
		.conversation-photo {
		width: 50px; /* Ajustez la taille de la photo selon vos besoins */
		height: 50px; /* Ajustez la taille de la photo selon vos besoins */
		border-radius: 50%; /* Rend la photo circulaire */
		margin-right: 10px; 
		}
		
        /* Style pour le bouton flottant */
        .add-button {
            position: fixed;
            bottom: 20px;
            right: 20px;
            background-color: #00a86b;
            color: white;
            border: none;
            border-radius: 50%;
            width: 50px;
            height: 50px;
            font-size: 24px;
            cursor: pointer;
        }
    </style>
</head>
<body>

	<div class="header">
		<h1>Chat&Fora</h1>
    <h1> {{ user.username}}</h1>
		<button id="btnOptions" class="options-button">Options</button>
	</div>
  <!-- Fenêtre d'options initialement cachée -->
	<div id="optionsWindow" style="display: none; position: fixed; top: 0; right: 0; width: 20%; height: 100%; background: #00a86b; z-index: 1000;">
	  <!-- Contenu de la fenêtre d'options -->
	</div>
	<div class="listOfconversations">
    <h1>Liste des conversations</h1>
    <ul class="conversation-list">
        
        {% for conversation in conversations %}
            <li class="conversation-item"><img src="{% static 'ressources/profile.jpeg' %}" alt = "C1" class="conversation-photo">
              <button class="btn-postuler" onclick="conversation({{ conversation.id }})">{{conversation.titre}}</button>
        {% empty %}
              <li> Aucune conversation disponible </li>
        {% endfor %}
    </ul>
	</div>

    <!-- Bouton flottant pour ajouter une nouvelle conversation -->
    <button class="add-button" onclick="create()">+</button>

      <script>
        function conversation(id) {
          // Redirection vers la page de candidature
          window.location.href = 'http://127.0.0.1:8000/Chat/messagerie/'+id+'/'; 
        }

        function create() {
          // Redirection vers la page de candidature
          window.location.href = 'http://127.0.0.1:8000/Chat/create'; 
        }
        // JavaScript : Logique pour afficher/cacher la fenêtre d'options
        document.getElementById('btnOptions').addEventListener('click', function() {
          var optionsWindow = document.getElementById('optionsWindow');
          if (optionsWindow.style.display === 'none') {
            optionsWindow.style.display = 'block'; // Affiche la fenêtre
          } else {
            optionsWindow.style.display = 'none'; // Cache la fenêtre
          }
        });
       </script>
</body>
</html>

Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/RegisterChat.html
<!--<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GetAJob - Inscription ou Visite</title>
<link rel="stylesheet" href="../Get A Job/style.css">
<link rel="stylesheet" href="Chat.css">

</head>
<body>

<header>
  <h1>Bienvenue sur les chats</h1>
</header>

<main>
  <section>
    <h2>Inscription</h2>
    <form id="inscriptionForm">
      <input type="text" id="nom" name="nom" placeholder="Votre nom" required>
      <input type="email" id="email" name="email" placeholder="Votre email" required>
      <input type="password" id="password" name="password" placeholder="Créez un mot de passe" required>
      <button type="submit">S'inscrire</button>
	  <button onclick="BackHome()">Annuler</button>
    </form>
  </section>

</main>

<footer>
  <p>Chats&Fora © 2024 . Tous droits réservés.</p>
</footer>

<script>
	document.getElementById('inscriptionForm').addEventListener('submit', function(event) {
  event.preventDefault();
  alert('Inscription réussie !');
});

function BackHome() {
  // Redirection vers la page des offres d'emploi
  window.location.href = '../Get A Job/Offres.html';
}
</script>
</body>
</html>
-->
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription Chat</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .form-container {
            width: 300px;
            margin: auto;
            margin-top: 50px;
        }
        input[type="text"],
        input[type="number"],
        button {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ddd;
        }
        button {
            background-color: #005948;
            color: white;
            cursor: pointer;
        }
        button:hover {
            opacity: 0.9;
        }
		
    </style>
</head>
<body>
    <div class="form-container">
        <h2>Inscription</h2>
        <input type="text" id="nom" placeholder="Nom">
        <input type="text" id="classe" placeholder="Classe">
        <input type="text" id="matricule" placeholder="Matricule">
        <button id="inscriptionBtn">S'inscrire/ S'authentifier</button>
    </div>
	
    <script>
        document.getElementById('inscriptionBtn').addEventListener('click', function() {
            var nom = document.getElementById('nom').value;
            var classe = document.getElementById('classe').value;
            var matricule = document.getElementById('matricule').value;
            
            // Ici, vous devriez ajouter le code pour enregistrer les données dans une base de données ou un autre système de stockage.
            console.log('Inscription:', nom, classe, matricule);
            
            // Réinitialiser le formulaire après l'inscription
            document.getElementById('nom').value = '';
            document.getElementById('classe').value = '';
            document.getElementById('matricule').value = '';
			
			window.location.href = 'http://127.0.0.1:8000/Chat/Acceuil';
        });
    </script>
</body>
</html>


Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/add_part.html
<script> alert("Erreur  \n \
    Utilisation non repertorié!!!");
    window.history.back();
</script>

Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/conversation_detail.html
{% block content %}
    <h1>Details de la conversation </h1>
    <h2>{{ conversation }}</h2>

    <div id="messages">
        {% for message in messages %}
        <div class="message">
            <p>{{ message.user.username }}</p>
            <p>{{ message.content }}-{{message.timestamp }}</p>

        </div>
        {% empty %}
        <p> Aucun message dans cette conversation.</p>
        {%endfor %}
    </div>

    <form id="message-form">
        <input type ="text" id="message-input" />
        <button type='submit'>  Envoyer</button>
    </form>

    <script>
        const socket = newWebSocket('http://127.0.0.1:8000/Chat/');
        // ouverture de la connexion Websocket d
        socket.onopen = () => {
            console.log('Connexion WebSocket établie.');};

        //reception de message du serveur
        socket.onmessage = (event) => {
            const data = JSON.parse(event.data);
            const message = data.message;
            // affichage du message du ser
        };
        // Gestion des erreurs de connexion Websocket 
        socket.onerror = (error) => {
            console.error('Erreur WebSocket :',error);
        };
        //Fermeture de la connexion WebSocket 
        socket.onclose = () => {
            console.log('Connexion WebSocket fermée.');
        };

        //Envoi du message au serveur via WebSocket 
        function sendmessage(message) {
            const data = {
                message: message
            };
            socket.send(JSON.stringify(data));
        } 
    </script>
{% endblock %}

Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/conversation_list.html
conversation 

Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/create_conversation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .form-container {
            width: 300px;
            margin: auto;
            margin-top: 50px;
        }
        input[type="text"],
        input[type="number"],
        button {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ddd;
        }
        button {
            background-color: #005948;
            color: white;
            cursor: pointer;
        }
        button:hover {
            opacity: 0.9;
        }
		
    </style>
</head>
<body>
    {% block content %}
    <div class="form-container">
         <h1>Creer une nouvelle conversation</h1>
         <form method="post" >
            {% csrf_token %}
            Utilisateurs connectés
            <select for="character_choice" name = "character_choice">
                {% for user in users %}
                <option value="{{ user}}">{{user}}</option>
                {% empty%}
                {% endfor %}
            </select>
            {{ form.as_p}}
            <button type="submit">Creer</button>
         </form>
    </div>
    {% endblock %}
</body>
</html>

Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/envoyer_message.html
<!-- envoyer_message.html -->
{% block content %}
<h1> Envoyer un message</h1>
<h2> {{ conversation}}</h2>

<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit"> Envoyer </button>
</form>


<h3> Message envoyes :</h3> 
<ul> {% for message in conversation.message_set.all %}
    <li>{{ message.content }}
-Envoye par 
{{ message.user.username}} le {{ message.timstamp}} </li>
{% endfor %}
    </ul>
    {% endblock %}

Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/erreur_user.html
<script> alert("Erreur  \n \
    Utilisation non repertorié!!!");
    window.history.back();
</script>

Hackathon_2024/Chat_Fora_S2/templates/Chat_Fora_S2/messagerie.html
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Application web de Messagerie</title>
<style>
  body, html {
    height: 100%;
    margin: 0;
    font-family: Arial, sans-serif;
  }
  
  /* Styles pour l'entête */
.header {
	position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: #00a86b;
  color: white;
  padding: 10px ;
  z-index: 999; /* Assurez-vous que l'entête est au-dessus du contenu */
}

/* Styles pour les boutons de l'entête */
.back-button,
.options-button {
  background-color: transparent;
  border: none;
  color: white;
  cursor: pointer;
  font-size: 16px;
}

  .chat-container {
    position: relative;
    height: 100%;
  }
  
  .chat-container::before{
	content: "";
	display: block;
	margin-top: 100px;
  }
  
  .messages-container {
    position: absolute;
    top: 0;
    bottom: 60px; /* Hauteur de l'input-container */
    left: 0;
    right: 0;
    overflow-y: auto;
    padding: 10px;
	padding-top: 500px;
  width :100% ;
  }
  .input-container {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: 100px;
    background-color: #f2f2f2;
    padding: 10px;
    box-sizing: border-box;
  }
  .input-container textarea {
    width: calc(100% - 190px);
    padding: 10px;
    /*margin-right: 10px;*/
    border: 1px solid #ccc;
    border-radius: 14px;
  }
  .input-container button {
    width: 100px;
    padding: 10px;
    background-color: #ff5945;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    margin 10px
  }
  .message {
    background-color: #e9e9eb;
    padding: 5px 10px;
    margin: 5px 0;
    border-radius: 14px;
  }
 
  #messages { list-style-type: none; padding: 0; }
  #messages li { padding: 5px 10px; }
  /*#messages li:nth-child(odd) */
  .received-message{
	color:#000;
	background: #eee; /* Couleur de fond pour les messages reçus */
	color: #000; /* Couleur du texte pour les messages reçus */
	text-align: leftt; /* Alignement du texte à droite */
	border-radius: 10px; /* Coins arrondis pour les messages */
	margin: 5px 0; /* Espacement entre les messages */
	margin-right:auto;
	max-width: 50%; /* Occupe la moitié du conteneur */
	width: fit-content;
	padding: 10px;
	}
  #input { margin-top: 10px; }
  /* Stylise les messages envoyés */
.sent-message {
  background-color: #009c5a; /* Couleur de fond pour les messages envoyés */
  color: #fff; /* Couleur du texte pour les messages envoyés */
  text-align: left; /* Alignement du texte à droite */
  border-radius: 10px; /* Coins arrondis pour les messages */
  margin: 5px 0; /* Espacement entre les messages */
  margin-left:auto;
  max-width: 50%; /* Occupe la moitié du conteneur */
  width: fit-content;
  padding: 10px;
}
</style>
</head>
<body>

{% block content %}
<div class="chat-container">
	<div class="header">
		<button onclick="back()" class="back-button">Retour</button>
		<h1 id="conversationName"> {{ conversation.titre }}</h1>
		<button class="options-button"></button>
    <button onclick="Add({{ conversation.id}})"> +        </button>
  </div>
  
  <div class="messages-container" id="messages">
    {% for message in messages %}
          {% if message.user == user %}
            <div class="sent-message">
              <p>{{ message.content }}</p>
              <p>{{message.timestamp }}</p>
            </div>
          {% else %}
            <div class="received-message">
              <p>{{ message.content }}</p>
              <p>{{message.timestamp }}</p>
            </div>
          {% endif %}
        
    {% empty %}
        <p> Aucun message dans cette conversation.</p>
    {%endfor %}
    
  </div>
  <div class="input-container">
    <form method="post" >
      {% csrf_token %}
      <textarea name ="content" placeholder="Entrer votre message ici "></textarea>
  
      <button type="submit"> Envoyer </button>
  </form>
    
  </div>
</div>


<script>
  const socket = newWebSocket('http://127.0.0.1:8000/Chat/');
  // ouverture de la connexion Websocket d
  socket.onopen = () => {
      console.log('Connexion WebSocket établie.');};

  //reception de message du serveur
  socket.onmessage = (event) => {
      const data = JSON.parse(event.data);
      const message = data.message;
      // affichage du message du ser
  };
  // Gestion des erreurs de connexion Websocket 
  socket.onerror = (error) => {
      console.error('Erreur WebSocket :',error);
  };
  //Fermeture de la connexion WebSocket 
  socket.onclose = () => {
      console.log('Connexion WebSocket fermée.');
  };

  //Envoi du message au serveur via WebSocket 
  function sendmessage(message) {
      const data = {
          message: message
      };
      socket.send(JSON.stringify(data));
  } 
//

  function back(){
	window.location.href = 'http://127.0.0.1:8000/Chat/Acceuil';
  }

  function Add(id){
   var  other = prompt('Entrez le nom du nouveau membre :');
    window.location.href = 'http://127.0.0.1:8000/Chat/add/'+id+other;
    }
    {% endblock %}
  // Sur la page de messagerie, au chargement du document
{% comment %} document.addEventListener('DOMContentLoaded', () => {
    // Récupérez le nom de la conversation et l'image
    const conversationName = sessionStorage.getItem('currentConversationName');
    
    // Mettez à jour l'interface avec le nom et l'image de la conversation
    document.getElementById('conversationName').textContent = conversationName;
}); {% endcomment %}

  
  {% comment %} document.addEventListener('DOMContentLoaded', loadMessages);

// Structure de l'objet message
function Message(text, isSent) {
  this.text = text;
  this.isSent = isSent;
  this.timestamp = new Date().toISOString();
} {% endcomment %}

{% comment %} // Enregistre un nouveau message dans le localStorage
function saveMessage(text, isSent) {
  var messages = JSON.parse(localStorage.getItem('messages')) || [];
  var message = new Message(text, isSent);
  messages.push(message);
  localStorage.setItem('messages', JSON.stringify(messages));
} {% endcomment %}

{% comment %} // Charge les messages au démarrage
function loadMessages() {
  var messages = JSON.parse(localStorage.getItem('messages')) || [];
  messages.forEach(function (message) {
    addMessageToDOM(message.text, message.isSent);
  });
} {% endcomment %}

{% comment %} // Ajoute un message au DOM
function addMessageToDOM(text, isSent) {
  
      var messagesContainer = document.getElementById('messages');
      var newMessageDiv = document.createElement('div');
      newMessageDiv.textContent = text;
	  if(isSent){
		newMessageDiv.classList.add('sent-message');
		}else{
			newMessageDiv.classList.add('received-message');
		}
      messagesContainer.appendChild(newMessageDiv);
      messagesContainer.scrollTop = messagesContainer.scrollHeight;
} {% endcomment %}

{% comment %} // Simule l'envoi d'un message
function sendMessage() {
  var input = document.getElementById('messageInput');
  var message = input.value.trim();
   if(message) {
	  input.value = '';
	  saveMessage(message, true); // true indique que le message est envoyé
	  addMessageToDOM(message, true);
  }
} {% endcomment %}

// Simule la réception d'un message
function receiveMessage(text) {
  saveMessage(text, false); // false indique que le message est reçu
  addMessageToDOM(text, false);
}


// Fonction pour simuler la réception d'un message après un délai
function receiveMessageAfterDelay(text, delay) {
  setTimeout(function() {
    receiveMessage(text);
  }, delay);
}

 //fonction qui vide le JSON
function clearMessages() {
  localStorage.removeItem('messages');
  console.log('Messages cleared successfully.');
} 



// Utilisation de la fonction pour vider les messages
clearMessages();
// Exemple d'utilisation
receiveMessageAfterDelay('Bonjour, comment ça va ?',1500);
receiveMessageAfterDelay('Moi ça va ',60000);
receiveMessageAfterDelay(' ça va bien merci', 30000);
receiveMessageAfterDelay('Bon bye',90000); 

</script>

</body>
</html>